output: "{{.Dir}}/README.md"
# header: |-
#   [![Go](https://github.com/engmtcdrm/go-entomb/actions/workflows/test.yml/badge.svg)](https://github.com/engmtcdrm/go-entomb/actions/workflows/test.yml)
#   [![Release](https://img.shields.io/github/v/release/engmtcdrm/go-entomb.svg?label=Latest%20Release)](https://github.com/engmtcdrm/go-entomb/releases/latest)
repository:
  url: https://github.com/engmtcdrm/go-pardon
  defaultBranch: main
  path: /
